name: 'Install Premake'
description: 'Downloads and executes Premake - https://premake.github.io/'
inputs:
  version:
    description: 'The version of Premake to download. Default: 5.0.0-beta3'
    required: true
    default: '5.0.0-beta4'
runs:
  using: 'node20'
  main: 'dist/index.js'
