name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: npm install
        run: npm install

      - name: Run tests
        run: npm test

  integration:
    name: Run Integration Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Premake
        uses: ./
        with:
          version: '5.0.0-beta4'

      - name: Check Premake
        run: premake5 --version
